// Generator version : v3.1
// DBC filename      : hytech_fd.dbc
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

#include "dbccodeconf.h"

#include "hytech.h"

typedef struct
{
  INV3_STATUS_t INV3_STATUS;
  INV3_TEMPS_t INV3_TEMPS;
  INV3_DYNAMICS_t INV3_DYNAMICS;
  INV3_POWER_t INV3_POWER;
  INV3_FEEDBACK_t INV3_FEEDBACK;
  INV4_STATUS_t INV4_STATUS;
  INV4_TEMPS_t INV4_TEMPS;
  INV4_DYNAMICS_t INV4_DYNAMICS;
  INV4_POWER_t INV4_POWER;
  INV4_FEEDBACK_t INV4_FEEDBACK;
  INV1_STATUS_t INV1_STATUS;
  INV1_TEMPS_t INV1_TEMPS;
  INV1_DYNAMICS_t INV1_DYNAMICS;
  INV1_POWER_t INV1_POWER;
  INV1_FEEDBACK_t INV1_FEEDBACK;
  INV2_STATUS_t INV2_STATUS;
  INV2_TEMPS_t INV2_TEMPS;
  INV2_DYNAMICS_t INV2_DYNAMICS;
  INV2_POWER_t INV2_POWER;
  INV2_FEEDBACK_t INV2_FEEDBACK;
  INV3_CONTROL_WORD_t INV3_CONTROL_WORD;
  INV4_CONTROL_WORD_t INV4_CONTROL_WORD;
  INV1_CONTROL_WORD_t INV1_CONTROL_WORD;
  INV2_CONTROL_WORD_t INV2_CONTROL_WORD;
  INV3_CONTROL_INPUT_t INV3_CONTROL_INPUT;
  INV4_CONTROL_INPUT_t INV4_CONTROL_INPUT;
  INV1_CONTROL_INPUT_t INV1_CONTROL_INPUT;
  PEDALS_SYSTEM_DATA_t PEDALS_SYSTEM_DATA;
  BMS_BOARD_DETAILED_TEMPS_t BMS_BOARD_DETAILED_TEMPS;
  BMS_VOLTAGES_t BMS_VOLTAGES;
  BMS_DETAILED_VOLTAGES_t BMS_DETAILED_VOLTAGES;
  BMS_TEMPS_t BMS_TEMPS;
  BMS_DETAILED_TEMPS_t BMS_DETAILED_TEMPS;
  BMS_STATUS_t BMS_STATUS;
  CCU_STATUS_t CCU_STATUS;
  REAR_SUSPENSION_t REAR_SUSPENSION;
  FRONT_SUSPENSION_t FRONT_SUSPENSION;
  REAR_THERMISTORS_DATA_t REAR_THERMISTORS_DATA;
  DRIVEBRAIN_TORQUE_LIM_INPUT_t DRIVEBRAIN_TORQUE_LIM_INPUT;
  DRIVEBRAIN_SPEED_SET_INPUT_t DRIVEBRAIN_SPEED_SET_INPUT;
  DRIVEBRAIN_DESIRED_TORQUE_INPUT_t DRIVEBRAIN_DESIRED_TORQUE_INPUT;
  DRIVEBRAIN_STEERING_INPUT_t DRIVEBRAIN_STEERING_INPUT;
  FRONT_THERMISTORS_t FRONT_THERMISTORS;
  EM_MEASUREMENT_t EM_MEASUREMENT;
  INV2_CONTROL_INPUT_t INV2_CONTROL_INPUT;
  INV3_CONTROL_PARAMETER_t INV3_CONTROL_PARAMETER;
  INV4_CONTROL_PARAMETER_t INV4_CONTROL_PARAMETER;
  INV1_CONTROL_PARAMETER_t INV1_CONTROL_PARAMETER;
  INV2_CONTROL_PARAMETER_t INV2_CONTROL_PARAMETER;
  ENERGY_METER_MEAS_t ENERGY_METER_MEAS;
  INV3_OVERLOAD_t INV3_OVERLOAD;
  INV4_OVERLOAD_t INV4_OVERLOAD;
  INV1_OVERLOAD_t INV1_OVERLOAD;
  INV2_OVERLOAD_t INV2_OVERLOAD;
  CAR_STATES_t CAR_STATES;
  DASH_INPUT_t DASH_INPUT;
  AERO_PRESSURE_SENSOR_22_t AERO_PRESSURE_SENSOR_22;
  AERO_PRESSURE_SENSOR_32_t AERO_PRESSURE_SENSOR_32;
  AERO_PRESSURE_SENSOR_42_t AERO_PRESSURE_SENSOR_42;
  AERO_PRESSURE_SENSOR_11_t AERO_PRESSURE_SENSOR_11;
  AERO_PRESSURE_SENSOR_12_t AERO_PRESSURE_SENSOR_12;
  EM_STATUS_t EM_STATUS;
  ENERGY_METER_STATUS_t ENERGY_METER_STATUS;
  STATE_OF_ENERGY_t STATE_OF_ENERGY;
  STATE_OF_CHARGE_t STATE_OF_CHARGE;
  STEERING_DATA_t STEERING_DATA;
  LF_TTPMS_1_t LF_TTPMS_1;
  LF_TTPMS_2_t LF_TTPMS_2;
  LF_TTPMS_3_t LF_TTPMS_3;
  LF_TTPMS_4_t LF_TTPMS_4;
  LF_TTPMS_5_t LF_TTPMS_5;
  LF_TTPMS_6_t LF_TTPMS_6;
  RF_TTPMS_1_t RF_TTPMS_1;
  RF_TTPMS_2_t RF_TTPMS_2;
  RF_TTPMS_3_t RF_TTPMS_3;
  RF_TTPMS_4_t RF_TTPMS_4;
  RF_TTPMS_5_t RF_TTPMS_5;
  RF_TTPMS_6_t RF_TTPMS_6;
  LR_TTPMS_1_t LR_TTPMS_1;
  LR_TTPMS_2_t LR_TTPMS_2;
  LR_TTPMS_3_t LR_TTPMS_3;
  LR_TTPMS_4_t LR_TTPMS_4;
  LR_TTPMS_5_t LR_TTPMS_5;
  LR_TTPMS_6_t LR_TTPMS_6;
  RR_TTPMS_1_t RR_TTPMS_1;
  RR_TTPMS_2_t RR_TTPMS_2;
  RR_TTPMS_3_t RR_TTPMS_3;
  RR_TTPMS_4_t RR_TTPMS_4;
  RR_TTPMS_5_t RR_TTPMS_5;
  RR_TTPMS_6_t RR_TTPMS_6;
  FL_BRAKE_ROTOR_TEMP_CH1_CH4_t FL_BRAKE_ROTOR_TEMP_CH1_CH4;
  FL_BRAKE_ROTOR_TEMP_CH5_CH8_t FL_BRAKE_ROTOR_TEMP_CH5_CH8;
  FL_BRAKE_ROTOR_TEMP_CH9_CH12_t FL_BRAKE_ROTOR_TEMP_CH9_CH12;
  FL_BRAKE_ROTOR_TEMP_CH13_CH16_t FL_BRAKE_ROTOR_TEMP_CH13_CH16;
  FL_BRAKE_ROTOR_SENSOR_TEMP_t FL_BRAKE_ROTOR_SENSOR_TEMP;
  FR_BRAKE_ROTOR_TEMP_CH1_CH4_t FR_BRAKE_ROTOR_TEMP_CH1_CH4;
  FR_BRAKE_ROTOR_TEMP_CH5_CH8_t FR_BRAKE_ROTOR_TEMP_CH5_CH8;
  FR_BRAKE_ROTOR_TEMP_CH9_CH12_t FR_BRAKE_ROTOR_TEMP_CH9_CH12;
  FR_BRAKE_ROTOR_TEMP_CH13_CH16_t FR_BRAKE_ROTOR_TEMP_CH13_CH16;
  FR_BRAKE_ROTOR_SENSOR_TEMP_t FR_BRAKE_ROTOR_SENSOR_TEMP;
  ACU_OK_t ACU_OK;
  DRIVEBRAIN_LATENCY_TIMES_t DRIVEBRAIN_LATENCY_TIMES;
  DRIVEBRAIN_LATENCY_STATUSES_t DRIVEBRAIN_LATENCY_STATUSES;
  FLOWMETER_DATA_t FLOWMETER_DATA;
  ENERGY_METER_TEMP_t ENERGY_METER_TEMP;
  AERO_PRESSURE_SENSOR_21_t AERO_PRESSURE_SENSOR_21;
  AERO_PRESSURE_SENSOR_31_t AERO_PRESSURE_SENSOR_31;
  AERO_PRESSURE_SENSOR_41_t AERO_PRESSURE_SENSOR_41;
  BRAKE_PRESSURE_t BRAKE_PRESSURE;
  VEHM_BETA_t VEHM_BETA;
  DASHBOARD_BUZZER_CONTROL_t DASHBOARD_BUZZER_CONTROL;
  FD_TEST_t FD_TEST;
  VEHM_ALPHA_t VEHM_ALPHA;
  CHARGER_CONTROL_t CHARGER_CONTROL;
  CHARGER_DATA_t CHARGER_DATA;
} hytech_rx_t;

// There is no any TX mapped massage.

uint32_t hytech_Receive(hytech_rx_t* m, const uint8_t* d, uint32_t msgid, uint8_t dlc);

#ifdef __DEF_HYTECH__

extern hytech_rx_t hytech_rx;

#endif // __DEF_HYTECH__

#ifdef __cplusplus
}
#endif
